### PR TITLE
fix notes about SugarML

### PR DESCRIPTION
**Pull request by olstenlarck**
doh.. the commit says Sugar**CSS** :D damn ocd...

Is it okey right now?

### CODE REVIEW

**Comment by jescalan** [comment]
Thank you, this is great! It's not quite accurate though - sugarml is not a dependency at all, so if you want to use it, it must be added as a dependency and required. This means it can be removed from the "includes" list, since the preset doesn't include it, and the code example given to enable it has to be changed a bit in order to be accurate.

**Comment by olstenlarck** [comment]
Actually, yea. But didn't want to update the example, cuz i'm not so familiar with it.

**Comment by jescalan** [comment]
Only one way to get familiar with things haha!

No worries though, just pushed a fix including all the examples. Thank you for taking a stab at this though, I appreciate it!

**Comment by olstenlarck** [comment]
great!

**Pull request closed without merging**
